apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-authserver
  template:
    metadata:
      labels:
        app: app-authserver
    spec:
      containers:
      - name: app-authserver
        image: hongyan5682/app-authserver:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-authserver
spec:
  selector:
    app: app-authserver
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80