apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: hongyan5682/auth-server:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-authserver
spec:
  selector:
    app: auth-server
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000