apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administration-service
  template:
    metadata:
      labels:
        app: administration-service
    spec:
      #assigned to master node
      nodeName: dgtestlinux02v
      containers:
      - name: administration-service
        image: hongyan5682/administration-service:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: administration-service
spec:
  selector:
    app: administration-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80