apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      #assigned to master node
      nodeName: dgtestlinux02v
      containers:
      - name: catalog-service
        image: hongyan5682/catalog-service:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 81
      targetPort: 81
      name: grpc