apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      #assigned to master node
      nodeName: dgtestlinux02v
      containers:
      - name: identity-service
        image: hongyan5682/identity-service:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      
    